// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"time"

	"github.com/google/uuid"
)

type Patient struct {
	PatientID uuid.UUID     `db:"patient_id"`
	FirstName string        `db:"first_name"`
	LastName  string        `db:"last_name"`
	Gender    string        `db:"gender"`
	Dob       time.Time     `db:"dob"`
	StaffID   uuid.NullUUID `db:"staff_id"`
	CreatedAt time.Time     `db:"created_at"`
	UpdatedAt time.Time     `db:"updated_at"`
}

type PatientAddress struct {
	PatientID uuid.UUID `db:"patient_id"`
	PlaceID   uuid.UUID `db:"place_id"`
	Line1     string    `db:"line_1"`
	City      string    `db:"city"`
	State     string    `db:"state"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type PatientContactInfo struct {
	PatientID uuid.UUID `db:"patient_id"`
	ContactID uuid.UUID `db:"contact_id"`
	Phone     string    `db:"phone"`
	Email     string    `db:"email"`
	Primary   bool      `db:"primary"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type PatientDiseas struct {
	PatientID uuid.UUID `db:"patient_id"`
	DiseasID  uuid.UUID `db:"diseas_id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}
