// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: patient_addresses.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CountPatientAddresses = `-- name: CountPatientAddresses :one
SELECT COUNT(*) FROM patient_addresses
`

func (q *Queries) CountPatientAddresses(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPatientAddresses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreatePatientAddress = `-- name: CreatePatientAddress :exec
INSERT INTO patient_addresses (
    patient_id,
    place_id,
    line_1,
    city,
    state,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePatientAddressParams struct {
	PatientID uuid.UUID `db:"patient_id"`
	PlaceID   uuid.UUID `db:"place_id"`
	Line1     string    `db:"line_1"`
	City      string    `db:"city"`
	State     string    `db:"state"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreatePatientAddress(ctx context.Context, arg CreatePatientAddressParams) error {
	_, err := q.db.ExecContext(ctx, CreatePatientAddress,
		arg.PatientID,
		arg.PlaceID,
		arg.Line1,
		arg.City,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const DeletePatientAddress = `-- name: DeletePatientAddress :exec
DELETE FROM patient_addresses
WHERE place_id = $1
`

func (q *Queries) DeletePatientAddress(ctx context.Context, placeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeletePatientAddress, placeID)
	return err
}

const GetPatientAddress = `-- name: GetPatientAddress :one
SELECT patient_id, place_id, line_1, city, state, created_at, updated_at
FROM patient_addresses
WHERE place_id = $1
LIMIT 1
`

func (q *Queries) GetPatientAddress(ctx context.Context, placeID uuid.UUID) (PatientAddress, error) {
	row := q.db.QueryRowContext(ctx, GetPatientAddress, placeID)
	var i PatientAddress
	err := row.Scan(
		&i.PatientID,
		&i.PlaceID,
		&i.Line1,
		&i.City,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetPatientAddressByPatientID = `-- name: GetPatientAddressByPatientID :one
SELECT patient_id, place_id, line_1, city, state, created_at, updated_at
FROM patient_addresses
WHERE patient_id = $1
LIMIT 1
`

func (q *Queries) GetPatientAddressByPatientID(ctx context.Context, patientID uuid.UUID) (PatientAddress, error) {
	row := q.db.QueryRowContext(ctx, GetPatientAddressByPatientID, patientID)
	var i PatientAddress
	err := row.Scan(
		&i.PatientID,
		&i.PlaceID,
		&i.Line1,
		&i.City,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListPatientAddresses = `-- name: ListPatientAddresses :many
SELECT patient_id, place_id, line_1, city, state, created_at, updated_at
FROM patient_addresses
ORDER BY created_at DESC
`

func (q *Queries) ListPatientAddresses(ctx context.Context) ([]PatientAddress, error) {
	rows, err := q.db.QueryContext(ctx, ListPatientAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatientAddress{}
	for rows.Next() {
		var i PatientAddress
		if err := rows.Scan(
			&i.PatientID,
			&i.PlaceID,
			&i.Line1,
			&i.City,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPatientAddressesByPatientID = `-- name: ListPatientAddressesByPatientID :many
SELECT patient_id, place_id, line_1, city, state, created_at, updated_at
FROM patient_addresses
WHERE patient_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPatientAddressesByPatientID(ctx context.Context, patientID uuid.UUID) ([]PatientAddress, error) {
	rows, err := q.db.QueryContext(ctx, ListPatientAddressesByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatientAddress{}
	for rows.Next() {
		var i PatientAddress
		if err := rows.Scan(
			&i.PatientID,
			&i.PlaceID,
			&i.Line1,
			&i.City,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdatePatientAddress = `-- name: UpdatePatientAddress :exec
UPDATE patient_addresses
SET
    line_1 = $2,
    city = $3,
    state = $4,
    updated_at = $5
WHERE place_id = $1
`

type UpdatePatientAddressParams struct {
	PlaceID   uuid.UUID `db:"place_id"`
	Line1     string    `db:"line_1"`
	City      string    `db:"city"`
	State     string    `db:"state"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) UpdatePatientAddress(ctx context.Context, arg UpdatePatientAddressParams) error {
	_, err := q.db.ExecContext(ctx, UpdatePatientAddress,
		arg.PlaceID,
		arg.Line1,
		arg.City,
		arg.State,
		arg.UpdatedAt,
	)
	return err
}
