// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: patients.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CountPatients = `-- name: CountPatients :one
SELECT COUNT(*) FROM patients
`

func (q *Queries) CountPatients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPatients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreatePatient = `-- name: CreatePatient :exec
INSERT INTO patients (
    patient_id,
    first_name,
    last_name,
    gender,
    dob,
    staff_id,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreatePatientParams struct {
	PatientID uuid.UUID     `db:"patient_id"`
	FirstName string        `db:"first_name"`
	LastName  string        `db:"last_name"`
	Gender    string        `db:"gender"`
	Dob       time.Time     `db:"dob"`
	StaffID   uuid.NullUUID `db:"staff_id"`
	CreatedAt time.Time     `db:"created_at"`
	UpdatedAt time.Time     `db:"updated_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) error {
	_, err := q.db.ExecContext(ctx, CreatePatient,
		arg.PatientID,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.Dob,
		arg.StaffID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const DeletePatient = `-- name: DeletePatient :exec
DELETE FROM patients
WHERE patient_id = $1
`

func (q *Queries) DeletePatient(ctx context.Context, patientID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeletePatient, patientID)
	return err
}

const GetPatient = `-- name: GetPatient :one
SELECT patient_id, first_name, last_name, gender, dob, staff_id, created_at, updated_at
FROM patients
WHERE patient_id = $1
LIMIT 1
`

func (q *Queries) GetPatient(ctx context.Context, patientID uuid.UUID) (Patient, error) {
	row := q.db.QueryRowContext(ctx, GetPatient, patientID)
	var i Patient
	err := row.Scan(
		&i.PatientID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Dob,
		&i.StaffID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListPatients = `-- name: ListPatients :many
SELECT patient_id, first_name, last_name, gender, dob, staff_id, created_at, updated_at
FROM patients
ORDER BY last_name ASC, first_name ASC
`

func (q *Queries) ListPatients(ctx context.Context) ([]Patient, error) {
	rows, err := q.db.QueryContext(ctx, ListPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.PatientID,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.Dob,
			&i.StaffID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdatePatient = `-- name: UpdatePatient :exec
UPDATE patients
SET
    first_name = $2,
    last_name = $3,
    gender = $4,
    dob = $5,
    staff_id = $6,
    updated_at = $7
WHERE patient_id = $1
`

type UpdatePatientParams struct {
	PatientID uuid.UUID     `db:"patient_id"`
	FirstName string        `db:"first_name"`
	LastName  string        `db:"last_name"`
	Gender    string        `db:"gender"`
	Dob       time.Time     `db:"dob"`
	StaffID   uuid.NullUUID `db:"staff_id"`
	UpdatedAt time.Time     `db:"updated_at"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) error {
	_, err := q.db.ExecContext(ctx, UpdatePatient,
		arg.PatientID,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.Dob,
		arg.StaffID,
		arg.UpdatedAt,
	)
	return err
}
