// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: patient_diseases.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CountPatientDiseases = `-- name: CountPatientDiseases :one
SELECT COUNT(*) FROM patient_diseases
`

func (q *Queries) CountPatientDiseases(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPatientDiseases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountPatientDiseasesByPatientID = `-- name: CountPatientDiseasesByPatientID :one
SELECT COUNT(*)
FROM patient_diseases
WHERE patient_id = $1
`

func (q *Queries) CountPatientDiseasesByPatientID(ctx context.Context, patientID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPatientDiseasesByPatientID, patientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreatePatientDiseas = `-- name: CreatePatientDiseas :exec
INSERT INTO patient_diseases (
    patient_id,
    diseas_id,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4)
`

type CreatePatientDiseasParams struct {
	PatientID uuid.UUID `db:"patient_id"`
	DiseasID  uuid.UUID `db:"diseas_id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreatePatientDiseas(ctx context.Context, arg CreatePatientDiseasParams) error {
	_, err := q.db.ExecContext(ctx, CreatePatientDiseas,
		arg.PatientID,
		arg.DiseasID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const DeletePatientDiseas = `-- name: DeletePatientDiseas :exec
DELETE FROM patient_diseases
WHERE patient_id = $1 AND diseas_id = $2
`

type DeletePatientDiseasParams struct {
	PatientID uuid.UUID `db:"patient_id"`
	DiseasID  uuid.UUID `db:"diseas_id"`
}

func (q *Queries) DeletePatientDiseas(ctx context.Context, arg DeletePatientDiseasParams) error {
	_, err := q.db.ExecContext(ctx, DeletePatientDiseas, arg.PatientID, arg.DiseasID)
	return err
}

const GetPatientDiseas = `-- name: GetPatientDiseas :one
SELECT patient_id, diseas_id, created_at, updated_at
FROM patient_diseases
WHERE patient_id = $1 AND diseas_id = $2
LIMIT 1
`

type GetPatientDiseasParams struct {
	PatientID uuid.UUID `db:"patient_id"`
	DiseasID  uuid.UUID `db:"diseas_id"`
}

func (q *Queries) GetPatientDiseas(ctx context.Context, arg GetPatientDiseasParams) (PatientDiseas, error) {
	row := q.db.QueryRowContext(ctx, GetPatientDiseas, arg.PatientID, arg.DiseasID)
	var i PatientDiseas
	err := row.Scan(
		&i.PatientID,
		&i.DiseasID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListPatientDiseases = `-- name: ListPatientDiseases :many
SELECT patient_id, diseas_id, created_at, updated_at
FROM patient_diseases
ORDER BY created_at DESC
`

func (q *Queries) ListPatientDiseases(ctx context.Context) ([]PatientDiseas, error) {
	rows, err := q.db.QueryContext(ctx, ListPatientDiseases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatientDiseas{}
	for rows.Next() {
		var i PatientDiseas
		if err := rows.Scan(
			&i.PatientID,
			&i.DiseasID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPatientDiseasesByDiseasID = `-- name: ListPatientDiseasesByDiseasID :many
SELECT patient_id, diseas_id, created_at, updated_at
FROM patient_diseases
WHERE diseas_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPatientDiseasesByDiseasID(ctx context.Context, diseasID uuid.UUID) ([]PatientDiseas, error) {
	rows, err := q.db.QueryContext(ctx, ListPatientDiseasesByDiseasID, diseasID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatientDiseas{}
	for rows.Next() {
		var i PatientDiseas
		if err := rows.Scan(
			&i.PatientID,
			&i.DiseasID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPatientDiseasesByPatientID = `-- name: ListPatientDiseasesByPatientID :many
SELECT patient_id, diseas_id, created_at, updated_at
FROM patient_diseases
WHERE patient_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPatientDiseasesByPatientID(ctx context.Context, patientID uuid.UUID) ([]PatientDiseas, error) {
	rows, err := q.db.QueryContext(ctx, ListPatientDiseasesByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatientDiseas{}
	for rows.Next() {
		var i PatientDiseas
		if err := rows.Scan(
			&i.PatientID,
			&i.DiseasID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdatePatientDiseas = `-- name: UpdatePatientDiseas :exec
UPDATE patient_diseases
SET
    updated_at = $3
WHERE patient_id = $1 AND diseas_id = $2
`

type UpdatePatientDiseasParams struct {
	PatientID uuid.UUID `db:"patient_id"`
	DiseasID  uuid.UUID `db:"diseas_id"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) UpdatePatientDiseas(ctx context.Context, arg UpdatePatientDiseasParams) error {
	_, err := q.db.ExecContext(ctx, UpdatePatientDiseas, arg.PatientID, arg.DiseasID, arg.UpdatedAt)
	return err
}
