// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: patient_contact_infos.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const CountPatientContactInfos = `-- name: CountPatientContactInfos :one
SELECT COUNT(*) FROM patient_contact_infos
`

func (q *Queries) CountPatientContactInfos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPatientContactInfos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreatePatientContactInfo = `-- name: CreatePatientContactInfo :exec
INSERT INTO patient_contact_infos (
    patient_id,
    contact_id,
    phone,
    email,
    "primary",
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePatientContactInfoParams struct {
	PatientID uuid.UUID `db:"patient_id"`
	ContactID uuid.UUID `db:"contact_id"`
	Phone     string    `db:"phone"`
	Email     string    `db:"email"`
	Primary   bool      `db:"primary"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

// SQL constants for mutations (used in repository)
func (q *Queries) CreatePatientContactInfo(ctx context.Context, arg CreatePatientContactInfoParams) error {
	_, err := q.db.ExecContext(ctx, CreatePatientContactInfo,
		arg.PatientID,
		arg.ContactID,
		arg.Phone,
		arg.Email,
		arg.Primary,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const DeletePatientContactInfo = `-- name: DeletePatientContactInfo :exec
DELETE FROM patient_contact_infos
WHERE contact_id = $1
`

func (q *Queries) DeletePatientContactInfo(ctx context.Context, contactID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeletePatientContactInfo, contactID)
	return err
}

const GetPatientContactInfo = `-- name: GetPatientContactInfo :one
SELECT patient_id, contact_id, phone, email, "primary", created_at, updated_at
FROM patient_contact_infos
WHERE contact_id = $1
LIMIT 1
`

func (q *Queries) GetPatientContactInfo(ctx context.Context, contactID uuid.UUID) (PatientContactInfo, error) {
	row := q.db.QueryRowContext(ctx, GetPatientContactInfo, contactID)
	var i PatientContactInfo
	err := row.Scan(
		&i.PatientID,
		&i.ContactID,
		&i.Phone,
		&i.Email,
		&i.Primary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetPatientContactInfoByPatientID = `-- name: GetPatientContactInfoByPatientID :one
SELECT patient_id, contact_id, phone, email, "primary", created_at, updated_at
FROM patient_contact_infos
WHERE patient_id = $1
LIMIT 1
`

func (q *Queries) GetPatientContactInfoByPatientID(ctx context.Context, patientID uuid.UUID) (PatientContactInfo, error) {
	row := q.db.QueryRowContext(ctx, GetPatientContactInfoByPatientID, patientID)
	var i PatientContactInfo
	err := row.Scan(
		&i.PatientID,
		&i.ContactID,
		&i.Phone,
		&i.Email,
		&i.Primary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListPatientContactInfos = `-- name: ListPatientContactInfos :many
SELECT patient_id, contact_id, phone, email, "primary", created_at, updated_at
FROM patient_contact_infos
ORDER BY created_at DESC
`

func (q *Queries) ListPatientContactInfos(ctx context.Context) ([]PatientContactInfo, error) {
	rows, err := q.db.QueryContext(ctx, ListPatientContactInfos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatientContactInfo{}
	for rows.Next() {
		var i PatientContactInfo
		if err := rows.Scan(
			&i.PatientID,
			&i.ContactID,
			&i.Phone,
			&i.Email,
			&i.Primary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPatientContactInfosByPatientID = `-- name: ListPatientContactInfosByPatientID :many
SELECT patient_id, contact_id, phone, email, "primary", created_at, updated_at
FROM patient_contact_infos
WHERE patient_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPatientContactInfosByPatientID(ctx context.Context, patientID uuid.UUID) ([]PatientContactInfo, error) {
	rows, err := q.db.QueryContext(ctx, ListPatientContactInfosByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatientContactInfo{}
	for rows.Next() {
		var i PatientContactInfo
		if err := rows.Scan(
			&i.PatientID,
			&i.ContactID,
			&i.Phone,
			&i.Email,
			&i.Primary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdatePatientContactInfo = `-- name: UpdatePatientContactInfo :exec
UPDATE patient_contact_infos
SET
    phone = $2,
    email = $3,
    "primary" = $4,
    updated_at = $5
WHERE contact_id = $1
`

type UpdatePatientContactInfoParams struct {
	ContactID uuid.UUID `db:"contact_id"`
	Phone     string    `db:"phone"`
	Email     string    `db:"email"`
	Primary   bool      `db:"primary"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) UpdatePatientContactInfo(ctx context.Context, arg UpdatePatientContactInfoParams) error {
	_, err := q.db.ExecContext(ctx, UpdatePatientContactInfo,
		arg.ContactID,
		arg.Phone,
		arg.Email,
		arg.Primary,
		arg.UpdatedAt,
	)
	return err
}
